### ISSUE TITLE
UXG-PRO Support? 

### ISSUE THREAD

**Issue by DigiDr** [boostchicken-dev/udm-utilities#356]
Hello,

Just trying to ascertain if there is support for the UXG-PRO now it's on general release. I see the stale thread from December, but has there been an update? How do i get this working?

**Comment by sprocktech** [comment]
As far as I can tell, this is the state of support for the UXG:

- UbiOS on the UXG is largely the same as the UDM
- However, there is a different podman container on the UXG, called "uxg-setup" instead of "unifi-os"
- This uxg-setup container isn't configurable like the unifi-os container, so packages can't be installed in it

All of this means that you can create and save scripts to the UXG, but nobody has found a way yet to automatically run them on boot like you can on a UDM.

@boostchicken I'm not a container wizard like yourself, but the only way I can think that this might work on a UXG would be to run a custom container (call it "uxg-utils" for instance) and install your on-boot-script and other packages in that. I don't know if or how this container would persist across reboots/updates though.

**Comment by AyberkAltuntop** [comment]
Hello,

What about the UDM-SE?

**Comment by gatesry** [comment]
> Hello,
> 
> What about the UDM-SE?

Hello,

UDM-SE is supported. Most content includes specific instructions for the SE variant.

**Comment by krvi** [comment]
Going by https://github.com/boostchicken-dev/udm-utilities/issues/69#issuecomment-792413718
I edited the `docker-entrypoint.sh` in the uxg-setup container to ssh "to it's host" and run a script.
```
docker exec uxg-setup sed -i '2i ssh -o StrictHostKeyChecking=no root@127.0.0.1 /mnt/data/startscript.sh' /usr/local/bin/docker-entrypoint.sh
```
This command, as well as `/mnt/data/*`, survives a shutdown/reboot and runs on start.
Does this help in any way?

**Comment by trilom** [comment]
https://gist.github.com/trilom/40fab563db416a69c63c127688ce7924

**Comment by boostchicken** [comment]
@trilom wanna PR that to the front page?

**Comment by joshuaspence** [comment]
I created my own gist, very similar to @trilom but with two variations:

1. Easy to execute (`curl https://gist.github.com/joshuaspence/a745426ab7d72631b1a4313f15e1774a | sh`)
2. Uses the same code as this repo to execute all files under `/mnt/data/on_boot.d` rather than just a single `/mnt/data/init.sh`.

**Comment by boostchicken** [comment]
@joshuaspence feel free to PR it!

**Comment by joshuaspence** [comment]
I have made some more progress and have managed to extract the `uxg-setup` image to my local machine. From there, I have modified the container to add the custom `docker-entrypoint.sh` and pushed the original and modified images to https://hub.docker.com/r/joshuaspence/uxg-setup.

To install the patched container, you can use `uxg-setup update`.

```
# uxg-setup update joshuaspence/uxg-setup
uxg-setup: Trying to pull docker.io/joshuaspence/uxg-setup...
uxg-setup: Getting image source signatures
uxg-setup: Copying blob sha256:098b7af5561c159eefb5ed6afb92387e7f5693381f7800abeaa
uxg-setup: Copying blob sha256:4ba47090b8e7030d1e06bcb06d411b85bef3c0ae29e0dee5b42
uxg-setup: Copying config sha256:e6dd8b977472abaea6beadb6ded1241597c51c2e0ec86bb7b
uxg-setup: Writing manifest to image destination
uxg-setup: Storing signatures
uxg-setup: e6dd8b977472abaea6beadb6ded1241597c51c2e0ec86bb760e38cc0c403bddb
uxg-setup: Stopping uxg-setup
uxg-setup: 3c06b69508f141976be09223b8ae87da040b8c7ea119760f1bae2a1f2915d5af
uxg-setup: 3c06b69508f141976be09223b8ae87da040b8c7ea119760f1bae2a1f2915d5af
uxg-setup: Starting uxg-setup
uxg-setup: podman create -d --name uxg-setup --label version=0.1.19 --network=host
uxg-setup: 4425ce2476b9b8a15cc2ad7863eed84b18d3d8af491e636da715396fbcfd438c
uxg-setup: uxg-setup
```

I am cleaning up the code a bit, but I have put everything I have into this repo: https://github.com/joshuaspence/uxg-setup

**Comment by boostchicken** [comment]
@joshuaspence I just merged @trilom PR, feel free to collab off his changes.

**Comment by boostchicken** [comment]
If you have a script that is fully automated that is great.  The users of this repo vary from Networking / Linux beginners to Linux Kernels devs, I try to cater to the lower end so it's more accessible.

**Comment by joshuaspence** [comment]
@boostchicken Since the approach taken (modifying the entrypoint of the `uxg-setup` container) wasn't my original idea and @trilom got his PR in before me I am not sure how to proceed exactly.

I don't think at this stage it makes sense to merge the progress to this repo, at least not using the approach I have taken in my repo. Basically, instead of patching the existing Docker container I am creating a new container with essentially the same patch. This method seems _slightly_ better because it persists through `uxg-setup reset`, which the local patch method does not (from memory, I could be wrong on this). This makes me hopeful that I might be able to persist the patch across upgrades, although I haven't verified this yet. One downside to this approach is that I need to create different versions of the container for each release of `uxg-setup`. Currently I am exporting this container from a real UXG-Pro that sits in my home network, which means it isn't feasible to have the code in this repo unless the maintainers have access to a UXG. I am thinking it should be possible to extract the container from firmware update files, which would remove this requirement.

@trilom if you wanted to continue developing the approach then I think it would be better to move it from a gist to a proper repo. I've been making improvements to my repo (https://github.com/joshuaspence/uxg-boot) and would be keen to collaborate with you on this.

**Comment by boostchicken** [comment]
Guess who just got a UXG :)

From your post your way sounds the ideal, we want to maintain going this being firmware upgrade proof.  

On the note of your build, I am happy to make you a maintainer here if you want to host it. Happy to link to your repo.  I suggest you move into this repo simply because of eyes.

Eventually I am going to have to explode all of this as the UDM/P,UDM-SE,UXG are all now supported.  UDR will be coming soon I am sure. I never imagined the project would get this far.  So if you have ideas let me know.

Also if you need some artifact hosting for your stuff I can give you access to my S3 bucket that serves out a boostchicken.dev

**Comment by boostchicken** [comment]
@joshuaspence FYI it should be pretty simple to get the container from the firmware with Binwalk

**Comment by joshuaspence** [comment]
I have made some more progress. I now extract the container from the publicly available firmware image from the Ubiquiti website, so access to real hardware isn't required.

I am happy to merge my changes in here. I do feel quite invested in my solution, having spent a long time refining the approach, but I agree that this would be more visible due to the success of this project.

An S3 bucket isn't required, but a Docker Registry is

**Comment by joshuaspence** [comment]
Thanks for the pointer. I used something else but might try `binwalk`

**Comment by boostchicken** [comment]
Your solution is more mature and documented at this point.  I don't think @trilom is too focused on this right now due to his lack of comments in this thread.  No matter!  Both of you got to the solution together and thats what counts.  We will adopt your solution.

Please up a PR merging your stuff as you see fit.  Feel free to re-work the main README.md so people can easily find their way to UDM vs UXG info.  Also, if you want to be a maintainer let me know.

I am about to start a new job so I maybe a bit spotty on github. Help is appreciated :)

Thanks @joshuaspence

**Comment by joshuaspence** [comment]
I agree on splitting this repo into multiple repos and so I am hesitant to merge all of my stuff in here. I think what makes sense to merge in right now is the install script. I could merge your `remote_install.sh` with my `install.sh` and I think that would cover the majority of users. More advanced users can dig in deeper if they want to.

I think this repo has evolved into mostly a collection of community driven scripts in addition to the "core" `on-boot-script`. I am interested in maintaining the `on-boot-script` functionality but to be honest I'm not keen on maintaining the various other scripts.

As a first step, I do think it makes sense to extract the `on-boot-script` directory out of this repo. I don't have a strong opinion at this stage on whether it makes sense to have a single repo for all devices or a repo per device. If this is something you are interested in, perhaps we could create a new GitHub org together.

**Comment by joshuaspence** [comment]
If anyone from Ubiquiti is reading this, it'd be really awesome to have native support for this functionality. Based on the popularity of this repo, there is definitely strong demand for it

**Comment by joshuaspence** [comment]
Also @boostchicken, for Podman binaries I had success (on the UXG at least) using the pre-built binaries from https://github.com/mgoltzsche/podman-static. Just one less thing for you to maintain if you want to use those

**Comment by joshuaspence** [comment]
Oh also, I tested my solution across a firmware update yesterday and it seemed to persist. I was "upgrading" to the same firmware version though, so possibly it didn't actually upgrade anything. I might test again with a downgrade then upgrade

**Comment by boostchicken** [comment]
> If anyone from Ubiquiti is reading this, it'd be really awesome to have native support for this functionality. Based on the popularity of this repo, there is definitely strong demand for it

Honestly, I think this repo is kind of the reason they don't.  It took me one month to rip apart everything after the UDMP came out and I got one. I simply wanted to run pihole on the thing.  There was a lot of bad press around the UDM/P because of its lack of features and I know at least a dozen people who bought or kept theirs because of this repo. You could not do simple things control fan speed, static routes weren't working, it was missing basic functionality (wpa_supplicant) and worst of all it was unstable. Certainly we have come a far way from those times, but I am absolutely positive this repo and all it's contributors made the UDM/P viable in those early days when it was half baked. 

The fact of the matter is, this repo is constantly discussed on their forums, reddit, ycombinator, is the subject of dozens of how to posts and blogs and they wont do it.  I have tons of metrics from my CDN, it's been downloaded hundreds of thousands of times. I am convinced it's because they have bad testing and the idea of letting users customize a device and supporting it is just too much for them.  

Also, I am sure they hate the support burden of someone who finds this repo and bricks their device haha.  When they added the TOS to the SSH banner I just hope they did it while muttering "boostchicken".

**Comment by boostchicken** [comment]
> Also @boostchicken, for Podman binaries I had success (on the UXG at least) using the pre-built binaries from https://github.com/mgoltzsche/podman-static. Just one less thing for you to maintain if you want to use those

So there are some subtle differences in my build, also I build more than podman (crio, criu, conmon, etc etc).  I certainly need to refactor the builds to automate them at the very least.

**Comment by boostchicken** [comment]
> Oh also, I tested my solution across a firmware update yesterday and it seemed to persist. I was "upgrading" to the same firmware version though, so possibly it didn't actually upgrade anything. I might test again with a downgrade then upgrade

That is all you need to test, a FW flash is a FW flash.

**Comment by boostchicken** [comment]
> I agree on splitting this repo into multiple repos and so I am hesitant to merge all of my stuff in here. I think what makes sense to merge in right now is the install script. I could merge your `remote_install.sh` with my `install.sh` and I think that would cover the majority of users. More advanced users can dig in deeper if they want to.
> 
> I think this repo has evolved into mostly a collection of community driven scripts in addition to the "core" `on-boot-script`. I am interested in maintaining the `on-boot-script` functionality but to be honest I'm not keen on maintaining the various other scripts.
> 
> As a first step, I do think it makes sense to extract the `on-boot-script` directory out of this repo. I don't have a strong opinion at this stage on whether it makes sense to have a single repo for all devices or a repo per device. If this is something you are interested in, perhaps we could create a new GitHub org together.

I think that makes a lot of sense.  So (udm-utilities, uxg-utilities, unifi-common) in a new organization?  We need a name for the new org.  Also I (or we) are going to have to re-do tons of links in this repo, thats nbd though, we can leave it up while we work at that.

Let's come up with a name and we can get it rolling

**Comment by joshuaspence** [comment]
I was thinking `unifi-utilities` (or `unifi-utils`) to show homage to this repo.

**Comment by boostchicken** [comment]
@joshuaspence sent you an email inviting you to the new org 

https://github.com/unifi-utilities

you can transfer your repository in there whenever you feel like it. move udm-utiliteis and refactoring into unifi-common will have to a bit more involved.

And with that I am closing this issue!

**Comment by boostchicken** [comment]
@joshuaspence 
https://app.bountysource.com/issues/98082586-unifi-uxg-pro-does-not-work?show_profile_modal=1

If i get the bounty I'll give it to you :)

**Comment by joshuaspence** [comment]
Moved my repo to https://github.com/unifi-utilities/uxg-boot. Thanks @boostchicken

**Comment by joeykrim** [comment]
> Oh also, I tested my solution across a firmware update yesterday and it seemed to persist. I was "upgrading" to the same firmware version though, so possibly it didn't actually upgrade anything. I might test again with a downgrade then upgrade

@joshuaspence  It worked for me, i.e. everything persisted and started up without any issues, when I upgraded from 1.11.0.3923 to 1.12.19.4302 on the UXG-Pro. Using version 0.1.19 of uxg-setup.
Thanks for the great work!
